# Generated by Django 5.1.2 on 2024-10-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='posicion_preferida',
            field=models.CharField(blank=True, choices=[('GK', 'Portero'), ('DF', 'Defensa'), ('MF', 'Centrocampista'), ('FW', 'Delantero')], max_length=2),
        ),
    ]
