# Generated by Django 5.1.2 on 2024-10-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_posicion_preferida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='posicion_preferida',
            field=models.CharField(blank=True, choices=[('PT', 'Portero'), ('DF', 'Defensa'), ('CC', 'Centrocampista'), ('DL', 'Delantero')], max_length=2),
        ),
    ]
